<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="TUnit" Version="1.66.27" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
  </ItemGroup>
</Project>
